### ISSUE TITLE
ブログを投稿したユーザの名前を、ブログ上に表示させる

### ISSUE THREAD

**Issue by aswork** [aswork/DIC_thema_lesson#1]
＃概要
「user_id」を定義する。

＃完了条件
-ユーザーとブログを紐付ける
-ブログにユーザー名が表示されるようにする

＃参考情報
DIVE09　アソシエーション

**Comment by norotime** [comment]
@aswork いいですね！この粒度はわかりやすいです！！
😸

**Comment by norotime** [comment]
@aswork 担当者をアサインしましょう！
https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/

**Comment by norotime** [comment]
@aswork  終わっていたら、クローズしましょう！
