### ISSUE TITLE
ブログ画面をBootstrap化する

### ISSUE THREAD

**Issue by mizutast** [aswork/DIC_thema_lesson#2]
## 概要
ブログ画面にBootstrapを適用する

## 完了条件
CRUD画面全てに適用させレスポンシブにする

## 参考情報
DIVE04_Bootstrap

**Comment by norotime** [comment]
@mizutast このイシュー名だと、何をして良いかがわからないですねーー。 😄

**Comment by norotime** [comment]
@mizutast 担当者をアサインしましょう！
https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/

**Comment by norotime** [comment]
@mizutast 終わっていたら、クローズしましょう！
